### ISSUE TITLE
Api problem?

### ISSUE THREAD

**Issue by PedroHGaspar** [adrianhajdin/project_react_native_jobs#3]
Heys guys, i'm getting this error: 

Object {
  "message": "Too many requests",
}

Request failed with status code 429
at node_modules\axios\lib\core\settle.js:null in settle
at node_modules\axios\lib\adapters\xhr.js:null in onloadend
- ... 10 more stack frames from framework internals

i did console.log(error.response.data) and it's appearing Too many requests.

Is this an API error? Because my home is appearing "something went wrong" on both popular and nearby.

**Comment by aaronjsharp** [comment]
I'm getting the same error. May be a limit on the free plan with the api service. I think it limits the amount of requests per second. I may try and add a timer to wait between requests for the popular and nearby job sections

**Comment by PedroHGaspar** [comment]
Any luck? I've tried to find some loop that i wall doing, but found nothing, my code is ok! The only error i'm getting is that i'vs used the API 1+ per second, and i think i was blocked... And i'm getting the error: (Property "item" doesn't exist). in the PopularJobCard

**Comment by jeffjiang13** [comment]
getting the same issue

**Comment by Jatan88** [comment]
For the issue where it sometimes shows popular jobs and sometimes nearby jobs, I made slight changes. I created another hook named "useFetcher" and made a second account on rapid api. The key I recieved from the second account I used it for useFetcher hook. Now I used useFetcher hook for fetching popular jobs and search functionality and useFetch hook for nearbyjobs.

For reference you can refer to my code : [https://github.com/Jatan88/JobSpot](url)

Please drop a like if you find it useful.

**Comment by PedroHGaspar** [comment]
It worked! Sometimes still get the message: "Something went wrong", but it works sometimes.

**Comment by Jatan88** [comment]
Actually, it should work every time. Anyways I am glad it worked for you too.
