### ISSUE TITLE
ScreenHeaderBtn(s) not getting displayed on the device screen

### ISSUE THREAD

**Issue by MayankB02** [adrianhajdin/project_react_native_jobs#8]
Hi Team, I have an android device, I am in the first 35 mins of the video, the screen header buttons are not getting displayed on my android device, only welcome, popularjobs and nearbyjobs, my code is same as that in the tutorial, can you pls suggest why this might be happening ?

**Comment by MayankB02** [comment]
Solved thanks.

**Comment by MayankB02** [comment]
Hi Team, I have an android device, I am in the first 35 mins of the video, the screen header buttons are not getting displayed on my android device, only welcome, popularjobs and nearbyjobs, my code is same as that in the tutorial, can you pls suggest why this might be happening ?

**Comment by codewriter3000** [comment]
I have the exact same issue on iPhone.

**Comment by codewriter3000** [comment]
Hey I think I figured out the issue: make sure you're wrapping your props in ScreenHeaderBtn with `{}`

**Comment by MayankB02** [comment]
Hi, can you please share the snippet ?

**Comment by MayankB02** [comment]
{ iconUrl, dimension, handlePress }, is this what you mean I am doing this as well

**Comment by MayankB02** [comment]
Figured, it out it was a silly syntax issue. Thanks.

**Comment by YSoSeriousMax** [comment]
I know its been solved already but just wanted to leave this for anyone out there.

I hade the same problem too, make sure you spell dimension and not dimensions in the index.js(home.js) file of the screenHeaderBtn component
