### ISSUE TITLE
ScreenHeaderBtn not showing

### ISSUE THREAD

**Issue by juanmarino15** [adrianhajdin/project_react_native_jobs#9]
Hello,

Has anyone had problems with the ScreenHeaderBtn to show in expoGo. I think is getting hidden behind the edges of the phone but not sure how to fix it.
I did make sure the code was the exact same as the one in the repo

**Comment by juanmarino15** [comment]
I was able to get it to show.

Had to delete all files and start from scratch.

**Comment by varundhand** [comment]
Im facing the same problem. They wont render on mine too

**Comment by varundhand** [comment]
Well it was silly syntax error, i used the wrong parenthesis
